project:
  type: website
  output-dir: docs

website:
  title: "Data Impact"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: posts/
        text: Blog

format:
  html:
    theme: cosmo
    toc: false
