project: 
  type: website
  output-dir: docs

website:
  title: "Data Impact"
  navbar: 
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Python"
        menu: 
          - text: "Pir치mide poblacional"
            href: "/Proyectos python/Distribuci칩n edades/C칩mo hacer un gr치fico de edades.qmd"